"""
Build `data/nat-full-data.js` — all nationalities with total applications and
overall grant rate for the latest complete year in the source.

Source: `asylum-claims-datasets-<YYYY>.xlsx` from gov.uk.
  https://www.gov.uk/government/statistical-data-sets/immigration-system-statistics-data-tables

Emits `window.NAT_FULL = [{name, v, grant}]` where:
  - `name` is the nationality
  - `v` is the count of claims (main applicants only) for the latest year
  - `grant` is the initial-decision grant rate (0–1) for that year, or None
    if no decisions were made for that nationality in the year

Usage:
    python scripts/build_nat_full.py <path/to/asylum-claims-datasets.xlsx> data/

Design
------
- Reads two sheets: `Data_Asy_D01` (applications) and `Data_Asy_D02` (decisions).
- Applications: filter `Applicant type == 'Main Applicant'`, sum `Claims` per
  nationality for the latest year present.
- Grant rate: for the same year, sum `Decisions` where `Case outcome group` is
  in ('Grant of Protection', 'Grant of Other Leave'), divide by total decisions.
- Output is deterministic and sorted by `v` descending.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd


GRANT_CATEGORIES = {"Grant of Protection", "Grant of Other Leave"}


def pick_latest_year(df: pd.DataFrame) -> int:
    """Latest year with all four quarters reported for Main Applicants."""
    main = df[df["Applicant type"] == "Main Applicant"]
    by_year = main.groupby("Year")["Quarter"].nunique()
    full_years = by_year[by_year >= 4].index
    if len(full_years) == 0:
        return int(by_year.index.max())
    return int(full_years.max())


def build_nat_full(xlsx_path: Path) -> tuple[list[dict], dict]:
    apps = pd.read_excel(xlsx_path, sheet_name="Data_Asy_D01", engine="openpyxl", header=1)
    dec = pd.read_excel(xlsx_path, sheet_name="Data_Asy_D02", engine="openpyxl", header=1)

    year = pick_latest_year(apps)

    apps_main = apps[(apps["Applicant type"] == "Main Applicant") & (apps["Year"] == year)]
    apps_by_nat = apps_main.groupby("Nationality")["Claims"].sum().astype(int)

    dec_main = dec[(dec["Applicant type"] == "Main Applicant") & (dec["Year"] == year)]
    dec_total_by_nat = dec_main.groupby("Nationality")["Decisions"].sum()
    dec_grant_by_nat = (
        dec_main[dec_main["Case outcome group"].isin(GRANT_CATEGORIES)]
        .groupby("Nationality")["Decisions"].sum()
    )

    rows: list[dict] = []
    for nat, v in apps_by_nat.items():
        if v <= 0:
            continue
        total_dec = int(dec_total_by_nat.get(nat, 0))
        grant_dec = int(dec_grant_by_nat.get(nat, 0))
        grant = (grant_dec / total_dec) if total_dec > 0 else None
        rows.append({"name": nat, "v": int(v), "grant": round(grant, 3) if grant is not None else None})

    rows.sort(key=lambda r: r["v"], reverse=True)

    meta = {
        "year": year,
        "source": xlsx_path.name,
        "generatedAt": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "provider": "UK Home Office",
        "licence": "Open Government Licence v3.0",
        "sourceUrl": "https://www.gov.uk/government/statistical-data-sets/immigration-system-statistics-data-tables",
    }
    return rows, meta


def write_js(out_dir: Path, rows: list[dict], meta: dict) -> Path:
    out = out_dir / "nat-full-data.js"
    body = (
        "/* AUTO-GENERATED by scripts/build_nat_full.py. Do not edit. */\n"
        f"window.NAT_FULL = {json.dumps(rows, ensure_ascii=False)};\n"
        f"window.NAT_FULL_META = {json.dumps(meta, ensure_ascii=False)};\n"
    )
    out.write_text(body, encoding="utf-8")
    return out


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("xlsx", type=Path, help="Path to asylum-claims-datasets .xlsx")
    p.add_argument("out_dir", type=Path, nargs="?", default=Path("data"),
                   help="Output directory (default: data/)")
    args = p.parse_args()

    if not args.xlsx.exists():
        print(f"error: {args.xlsx} does not exist", file=sys.stderr)
        return 2
    args.out_dir.mkdir(parents=True, exist_ok=True)

    rows, meta = build_nat_full(args.xlsx)
    out = write_js(args.out_dir, rows, meta)
    print(f"wrote {out} - {len(rows)} nationalities, year {meta['year']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
