"""
Build `data/backlog-data.js` — annual backlog of asylum claims pending an
initial decision, using year-end (31 Dec) snapshots from Asy_D03.

Source: `asylum-claims-awaiting-decision-datasets-<mmm-YYYY>.xlsx`
  https://www.gov.uk/government/statistical-data-sets/immigration-system-statistics-data-tables

Emits:
  window.BACKLOG_LATEST = [{y, v, date}]   — y is calendar year, v is pending-
                                              initial-decision count (main
                                              applicants), date is snapshot label
  window.BACKLOG_META   = {latest_year, latest_date, source, ...}

Usage:
    python scripts/build_backlog.py <path/to/awaiting-decision.xlsx> data/

Design
------
- Reads Data_Asy_D03, filters to Main Applicant + Pending initial decision.
- Uses the 31 Dec snapshot for each year as the canonical year-end figure.
- Series starts from 2018 to match the existing shell chart range.
- Latest year may be a partial-year snapshot (e.g. Sep 2025) if Dec is not yet
  published; in that case the row is included with date label for transparency.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd


SERIES_START = 2018
APP_STAGE = "Pending initial decision"
APP_TYPE = "Main Applicant"


def build_backlog(xlsx_path: Path) -> tuple[list[dict], dict]:
    df = pd.read_excel(xlsx_path, sheet_name="Data_Asy_D03", engine="openpyxl", header=1)
    date_col = df.columns[0]

    # Parse dates — stored as strings like "31 Dec 2023".
    df["_date"] = pd.to_datetime(df[date_col], format="%d %b %Y", errors="coerce")
    df["_year"] = df["_date"].dt.year
    df["_month"] = df["_date"].dt.month

    main = df[
        (df["Applicant type"] == APP_TYPE) &
        (df["Application stage"] == APP_STAGE)
    ].copy()

    # For each year, prefer the 31 Dec snapshot; fall back to the latest available.
    rows: list[dict] = []
    for year in range(SERIES_START, df["_year"].max() + 1):
        year_data = main[main["_year"] == year]
        if year_data.empty:
            continue
        dec_data = year_data[year_data["_month"] == 12]
        snap = dec_data if not dec_data.empty else year_data.sort_values("_date").tail(1)
        snap_date = snap["_date"].iloc[0]
        total = int(snap["Claims"].sum())
        if total <= 0:
            continue
        rows.append({
            "y": year,
            "v": total,
            "date": snap_date.strftime("%d %b %Y").lstrip("0") if hasattr(snap_date, 'strftime') else str(snap_date)[:10],
        })

    rows.sort(key=lambda r: r["y"])

    latest_row = rows[-1] if rows else {}
    meta = {
        "latest_year": latest_row.get("y"),
        "latest_date": latest_row.get("date"),
        "series_start": SERIES_START,
        "source": xlsx_path.name,
        "generatedAt": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "provider": "UK Home Office",
        "licence": "Open Government Licence v3.0",
        "sourceUrl": (
            "https://www.gov.uk/government/statistical-data-sets/"
            "immigration-system-statistics-data-tables"
        ),
        "notes": (
            "Annual figures use the 31 December snapshot for each year. "
            "Counts main applicants pending an initial decision only. "
            "Source: Asy_D03."
        ),
    }
    return rows, meta


def write_js(out_dir: Path, rows: list[dict], meta: dict) -> Path:
    out = out_dir / "backlog-data.js"
    body = (
        "/* AUTO-GENERATED by scripts/build_backlog.py. Do not edit. */\n"
        f"window.BACKLOG_LATEST = {json.dumps(rows, ensure_ascii=False)};\n"
        f"window.BACKLOG_META   = {json.dumps(meta, ensure_ascii=False)};\n"
    )
    out.write_text(body, encoding="utf-8")
    return out


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("xlsx", type=Path, help="Path to awaiting-decision .xlsx")
    p.add_argument("out_dir", type=Path, nargs="?", default=Path("data"),
                   help="Output directory (default: data/)")
    args = p.parse_args()

    if not args.xlsx.exists():
        print(f"error: {args.xlsx} does not exist", file=sys.stderr)
        return 2
    args.out_dir.mkdir(parents=True, exist_ok=True)

    rows, meta = build_backlog(args.xlsx)
    out = write_js(args.out_dir, rows, meta)
    latest = rows[-1] if rows else {}
    print(f"wrote {out} — {len(rows)} years, latest {latest.get('y')} ({latest.get('date')}): {latest.get('v', 0):,}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
