"""
Build `data/nat-grant-annual-data.js` — annual grant-rate time series per
nationality, for the top nationalities that appear consistently in D02.

Source: `asylum-claims-datasets-<YYYY>.xlsx` from gov.uk.
  Sheet: Data_Asy_D02

Emits:
  window.NAT_GRANT_ANNUAL = {
    years: [2009, 2010, ..., 2025],
    series: [
      { name: "Afghanistan", data: [0.85, 0.91, ...] },   // grant rate 0-1, null if no decisions
      ...
    ]
  }
  window.NAT_GRANT_ANNUAL_META = {latest_year, source, generatedAt, ...}

Design:
- Main applicants only.
- Grant rate = (Grant of Protection + Grant of Other Leave) / total decisions.
- Nationalities included: top MIN_DECISIONS_THRESHOLD nationalities by total
  decisions across the whole series, keeping those with data in at least
  MIN_YEARS years.
- Null for years where a nationality had no initial decisions.
- Series starts 2009 (consistent Age/Sex data; before this decisions data is
  present but less granular).

Usage:
    python scripts/build_nat_grant_annual.py <path/to/asylum-claims-datasets.xlsx> data/
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

SERIES_START = 2009
GRANT_CATEGORIES = {"Grant of Protection", "Grant of Other Leave"}
MIN_TOTAL_DECISIONS = 200   # minimum cumulative decisions across series to include a nationality
MIN_YEARS = 5               # minimum years with decisions to include a nationality


def build_nat_grant_annual(xlsx_path: Path) -> tuple[dict, dict]:
    dec = pd.read_excel(xlsx_path, sheet_name="Data_Asy_D02", engine="openpyxl", header=1)

    main = dec[
        (dec["Applicant type"] == "Main Applicant") &
        (dec["Year"] >= SERIES_START)
    ].copy()

    years = sorted(main["Year"].unique().tolist())

    # Total and grant decisions per (Year, Nationality)
    total_by = main.groupby(["Year", "Nationality"])["Decisions"].sum()
    grant_by = (
        main[main["Case outcome group"].isin(GRANT_CATEGORIES)]
        .groupby(["Year", "Nationality"])["Decisions"].sum()
    )

    # Nationalities with enough data
    total_all = main.groupby("Nationality")["Decisions"].sum()
    years_covered = main.groupby("Nationality")["Year"].nunique()
    eligible = total_all[
        (total_all >= MIN_TOTAL_DECISIONS) &
        (years_covered >= MIN_YEARS)
    ].sort_values(ascending=False).index.tolist()

    series = []
    for nat in eligible:
        data = []
        for yr in years:
            total = int(total_by.get((yr, nat), 0))
            if total == 0:
                data.append(None)
            else:
                granted = int(grant_by.get((yr, nat), 0))
                data.append(round(granted / total, 3))
        series.append({"name": nat, "data": data})

    # Sort by latest-year grant rate descending (nulls last), then by name
    def sort_key(s):
        last = next((v for v in reversed(s["data"]) if v is not None), None)
        return (last is None, -(last or 0), s["name"])
    series.sort(key=sort_key)

    result = {"years": [int(y) for y in years], "series": series}

    latest_year = int(years[-1]) if years else None
    meta = {
        "latest_year": latest_year,
        "series_start": SERIES_START,
        "nationalities": len(series),
        "source": xlsx_path.name,
        "generatedAt": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "provider": "UK Home Office",
        "licence": "Open Government Licence v3.0",
        "sourceUrl": (
            "https://www.gov.uk/government/statistical-data-sets/"
            "immigration-system-statistics-data-tables"
        ),
        "notes": (
            "Main applicants only. Grant rate = (Grant of Protection + Grant of Other Leave) "
            "/ total decisions. Nationalities with fewer than "
            f"{MIN_TOTAL_DECISIONS} total decisions or data in fewer than {MIN_YEARS} years excluded."
        ),
    }
    return result, meta


def write_js(out_dir: Path, result: dict, meta: dict) -> Path:
    out = out_dir / "nat-grant-annual-data.js"
    body = (
        "/* AUTO-GENERATED by scripts/build_nat_grant_annual.py. Do not edit. */\n"
        f"window.NAT_GRANT_ANNUAL      = {json.dumps(result, ensure_ascii=False)};\n"
        f"window.NAT_GRANT_ANNUAL_META = {json.dumps(meta, ensure_ascii=False)};\n"
    )
    out.write_text(body, encoding="utf-8")
    return out


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("xlsx", type=Path, help="Path to asylum-claims-datasets .xlsx")
    p.add_argument("out_dir", type=Path, nargs="?", default=Path("data"),
                   help="Output directory (default: data/)")
    args = p.parse_args()

    if not args.xlsx.exists():
        print(f"error: {args.xlsx} does not exist", file=sys.stderr)
        return 2
    args.out_dir.mkdir(parents=True, exist_ok=True)

    result, meta = build_nat_grant_annual(args.xlsx)
    out = write_js(args.out_dir, result, meta)
    print(
        f"wrote {out} — {meta['nationalities']} nationalities, "
        f"{len(result['years'])} years ({result['years'][0]}–{result['years'][-1]})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
