"""
Build `data/age-assessments-data.js` — people subject to age assessments,
raised and closed by nationality, latest complete year in the source.

Source: `age-assessments-detailed-datasets-<mmm-YYYY>.xlsx` from gov.uk.
  https://www.gov.uk/government/statistical-data-sets/immigration-system-statistics-data-tables

Emits `window.AGE_ASSESSMENTS_BY_NATIONALITY = [{name, region, raised, resolved_over_18, resolved_under_18}]`
and `window.AGE_ASSESSMENTS_META = {...}`.

Usage:
    python scripts/build_age_assessments.py <path/to/age-assessments-detailed-datasets.xlsx> data/

Design
------
- Reads sheet `Data_Age_D01` ("people subject to age assessments, by earliest
  raised date").
- `raised` sums People on rows where `Raised / Closed` == 'Raised'.
- `resolved_over_18` / `resolved_under_18` split rows where `Raised / Closed`
  == 'Closed' by the `Assessed age` outcome ('18+' vs 'Under 18').
- Output keys (raised / resolved_over_18 / resolved_under_18) are kept from the
  predecessor "age disputes" dataset so downstream charts read unchanged.
  "Resolved" here means the assessment was closed with an age outcome.
- Sorted by raised desc, deterministic.

History: replaces build_age_disputes.py. gov.uk retired the "age disputes
detailed datasets" table on 21 May 2026 in favour of the broader "age
assessments detailed datasets".
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd


def pick_latest_year(df: pd.DataFrame) -> int:
    """Latest year with all four quarters reported."""
    by_year = df.groupby("Year")["Quarter"].nunique()
    full_years = by_year[by_year >= 4].index
    if len(full_years) == 0:
        return int(by_year.index.max())
    return int(full_years.max())


def build_age_assessments(xlsx_path: Path) -> tuple[list[dict], dict]:
    df = pd.read_excel(xlsx_path, sheet_name="Data_Age_D01", engine="openpyxl", header=1)

    year = pick_latest_year(df)
    latest = df[df["Year"] == year]

    raised = (
        latest[latest["Raised / Closed"] == "Raised"]
        .groupby(["Nationality", "Region"])["People"].sum()
    )
    resolved_over = (
        latest[(latest["Raised / Closed"] == "Closed") &
               (latest["Assessed age"] == "18+")]
        .groupby(["Nationality", "Region"])["People"].sum()
    )
    resolved_under = (
        latest[(latest["Raised / Closed"] == "Closed") &
               (latest["Assessed age"] == "Under 18")]
        .groupby(["Nationality", "Region"])["People"].sum()
    )

    keys = sorted(
        set(raised.index) | set(resolved_over.index) | set(resolved_under.index),
        key=lambda k: (-int(raised.get(k, 0)), k[0])
    )

    rows: list[dict] = []
    for (nat, region) in keys:
        r = int(raised.get((nat, region), 0))
        ro = int(resolved_over.get((nat, region), 0))
        ru = int(resolved_under.get((nat, region), 0))
        if r == 0 and ro == 0 and ru == 0:
            continue
        rows.append({
            "name": nat,
            "region": region,
            "raised": r,
            "resolved_over_18": ro,
            "resolved_under_18": ru,
        })

    meta = {
        "year": year,
        "source": xlsx_path.name,
        "generatedAt": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "provider": "UK Home Office",
        "licence": "Open Government Licence v3.0",
        "sourceUrl": "https://www.gov.uk/government/statistical-data-sets/immigration-system-statistics-data-tables",
    }
    return rows, meta


def write_js(out_dir: Path, rows: list[dict], meta: dict) -> Path:
    out = out_dir / "age-assessments-data.js"
    body = (
        "/* AUTO-GENERATED by scripts/build_age_assessments.py. Do not edit. */\n"
        f"window.AGE_ASSESSMENTS_BY_NATIONALITY = {json.dumps(rows, ensure_ascii=False)};\n"
        f"window.AGE_ASSESSMENTS_META = {json.dumps(meta, ensure_ascii=False)};\n"
    )
    out.write_text(body, encoding="utf-8")
    return out


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("xlsx", type=Path, help="Path to age-assessments-detailed-datasets .xlsx")
    p.add_argument("out_dir", type=Path, nargs="?", default=Path("data"),
                   help="Output directory (default: data/)")
    args = p.parse_args()

    if not args.xlsx.exists():
        print(f"error: {args.xlsx} does not exist", file=sys.stderr)
        return 2
    args.out_dir.mkdir(parents=True, exist_ok=True)

    rows, meta = build_age_assessments(args.xlsx)
    out = write_js(args.out_dir, rows, meta)
    print(f"wrote {out} - {len(rows)} nationalities, year {meta['year']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
