"""
Build `data/hotels-data.js` - quarterly snapshots of persons in contingency
hotel accommodation.

Source: `asylum-seekers-receipt-support-datasets-<mmm-YYYY>.xlsx` from gov.uk.
  https://www.gov.uk/government/statistical-data-sets/immigration-system-statistics-data-tables

Emits `window.HOTELS = [{date, persons_in_hotels}]` where:
  - `date` is the snapshot date (ISO `YYYY-MM-DD`)
  - `persons_in_hotels` is the sum of People where Accommodation Type is
    'Contingency Accommodation - Hotel'

Usage:
    python scripts/build_hotels.py <path/to/asylum-seekers-receipt-support-datasets.xlsx> data/

Design
------
- Reads `Data_Asy_D09`. Filter `Accommodation Type == 'Contingency
  Accommodation - Hotel'`, sum `People` per `Date (as at )`.
- Hotel-contingency accommodation only appears from ~2020 onwards; pre-2020
  dates with zero hotel residents are dropped from the output (skip, don't
  plot zero - per CLAUDE.md).
- Output is sorted by date ascending.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd


HOTEL_LABEL = "Contingency Accommodation - Hotel"


def parse_date(raw) -> str:
    """'31 Mar 2020' -> '2020-03-31'. Accept pandas Timestamp passthrough."""
    if isinstance(raw, pd.Timestamp):
        return raw.date().isoformat()
    return datetime.strptime(str(raw).strip(), "%d %b %Y").date().isoformat()


def build_hotels(xlsx_path: Path) -> tuple[list[dict], dict]:
    df = pd.read_excel(xlsx_path, sheet_name="Data_Asy_D09", engine="openpyxl", header=1)

    # The "Date (as at )" header contains a non-breaking space in the source.
    # Resolve it by matching whichever column starts with "Date".
    date_col = next(c for c in df.columns if str(c).startswith("Date"))

    hotel = df[df["Accommodation Type"] == HOTEL_LABEL]
    by_date = hotel.groupby(date_col)["People"].sum()

    rows: list[dict] = []
    for raw_date, persons in by_date.items():
        p = int(persons)
        if p <= 0:
            continue
        rows.append({"date": parse_date(raw_date), "persons_in_hotels": p})

    rows.sort(key=lambda r: r["date"])

    meta = {
        "source": xlsx_path.name,
        "generatedAt": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "provider": "UK Home Office",
        "licence": "Open Government Licence v3.0",
        "sourceUrl": "https://www.gov.uk/government/statistical-data-sets/immigration-system-statistics-data-tables",
        "accommodationType": HOTEL_LABEL,
        "snapshots": len(rows),
    }
    return rows, meta


def write_js(out_dir: Path, rows: list[dict], meta: dict) -> Path:
    out = out_dir / "hotels-data.js"
    body = (
        "/* AUTO-GENERATED by scripts/build_hotels.py. Do not edit. */\n"
        f"window.HOTELS = {json.dumps(rows, ensure_ascii=False)};\n"
        f"window.HOTELS_META = {json.dumps(meta, ensure_ascii=False)};\n"
    )
    out.write_text(body, encoding="utf-8")
    return out


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("xlsx", type=Path, help="Path to asylum-seekers-receipt-support-datasets .xlsx")
    p.add_argument("out_dir", type=Path, nargs="?", default=Path("data"))
    args = p.parse_args()

    if not args.xlsx.exists():
        print(f"error: {args.xlsx} does not exist", file=sys.stderr)
        return 2
    args.out_dir.mkdir(parents=True, exist_ok=True)

    rows, meta = build_hotels(args.xlsx)
    out = write_js(args.out_dir, rows, meta)
    if rows:
        print(f"wrote {out} - {len(rows)} snapshots ({rows[0]['date']} -> {rows[-1]['date']}); "
              f"latest = {rows[-1]['persons_in_hotels']:,} in hotels")
    else:
        print(f"wrote {out} - 0 snapshots (no hotel rows found)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
