"""
Build `data/support-regions-data.js` — asylum seekers in receipt of Home
Office support, from Asy_D11.

Source: `support-local-authority-datasets-<mmm-YYYY>.xlsx`
  https://www.gov.uk/government/statistical-data-sets/immigration-system-statistics-data-tables

Emits three globals:
  window.SUPPORT_REGIONS = [{name, v}]          — latest snapshot, by region
  window.SUPPORT_REGIONS_META = {date, ...}
  window.SUPPORT_TIERS_LATEST = {date, s95, s98, s4, total}
  window.SUPPORT_TIERS_ANNUAL = [{date, s95, s98, s4, total}]  — all snapshots

Usage:
    python scripts/build_support_regions.py <path/to/support-la.xlsx> data/

Design
------
- Reads Data_Asy_D11; sums People by 'UK Region / Nation' at the latest
  snapshot date, across all support types (S95 + S98 + S4).
- Excludes rows where the region is 'N/A', 'Unknown', or blank — these are
  legacy / uncategorised support buckets with no geographic meaning.
- Tiers output keeps the three Sections separate without changing the regional
  totals — by construction S95 + S98 + S4 equals the summed regional total for
  the same snapshot.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd


# Regions to exclude — historic/uncategorised buckets.
EXCLUDE = {
    "N/A - Section 4 (pre-2018)",
    "N/A - Section 98 (pre-Dec 2022)",
    "N/A - Subsistence Only (Dec 2023 - Dec 2024)",
    "Unknown",
}

# Normalise minor capitalisation differences.
NORMALISE = {
    "East Of England": "East of England",
    "Yorkshire And The Humber": "Yorkshire & The Humber",
    "Yorkshire and The Humber": "Yorkshire & The Humber",
}


TIER_KEYS = {"Section 95": "s95", "Section 98": "s98", "Section 4": "s4"}


def _fmt_date(d) -> str:
    return d.strftime("%d %b %Y").lstrip("0") if hasattr(d, "strftime") else str(d)[:10]


def build_support(xlsx_path: Path) -> tuple[list[dict], dict, dict, list[dict]]:
    df = pd.read_excel(xlsx_path, sheet_name="Data_Asy_D11", engine="openpyxl", header=1)
    date_col = df.columns[0]

    df["_date"] = pd.to_datetime(df[date_col], format="%d %b %Y", errors="coerce")
    latest_date = df["_date"].max()

    latest = df[df["_date"] == latest_date].copy()
    latest["_region"] = latest["UK Region / Nation"].map(lambda r: NORMALISE.get(r, r))

    keep = latest[~latest["_region"].isin(EXCLUDE) & latest["_region"].notna()]
    by_region = keep.groupby("_region")["People"].sum().reset_index()
    by_region = by_region[by_region["People"] > 0].sort_values("People", ascending=False)

    rows = [{"name": str(r["_region"]), "v": int(r["People"])} for _, r in by_region.iterrows()]

    meta = {
        "date": _fmt_date(latest_date),
        "source": xlsx_path.name,
        "generatedAt": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "provider": "UK Home Office",
        "licence": "Open Government Licence v3.0",
        "sourceUrl": (
            "https://www.gov.uk/government/statistical-data-sets/"
            "immigration-system-statistics-data-tables"
        ),
        "notes": (
            "People in receipt of Home Office support (Section 95/98/4) by UK region "
            "at the latest published snapshot. This is where asylum seekers are housed, "
            "not where initial claims were lodged. Source: Asy_D11."
        ),
    }

    tier_totals = (
        df.groupby(["_date", "Support Type"])["People"].sum().unstack(fill_value=0)
    )
    annual: list[dict] = []
    for dt, row in tier_totals.iterrows():
        if pd.isna(dt):
            continue
        s95 = int(row.get("Section 95", 0))
        s98 = int(row.get("Section 98", 0))
        s4 = int(row.get("Section 4", 0))
        annual.append({
            "date": _fmt_date(dt),
            "s95": s95,
            "s98": s98,
            "s4": s4,
            "total": s95 + s98 + s4,
        })
    annual.sort(key=lambda r: pd.to_datetime(r["date"], format="%d %b %Y"))
    tiers_latest = annual[-1] if annual else {"date": meta["date"], "s95": 0, "s98": 0, "s4": 0, "total": 0}

    return rows, meta, tiers_latest, annual


def write_js(out_dir: Path, rows: list[dict], meta: dict, tiers_latest: dict, annual: list[dict]) -> Path:
    out = out_dir / "support-regions-data.js"
    body = (
        "/* AUTO-GENERATED by scripts/build_support_regions.py. Do not edit. */\n"
        f"window.SUPPORT_REGIONS = {json.dumps(rows, ensure_ascii=False)};\n"
        f"window.SUPPORT_REGIONS_META = {json.dumps(meta, ensure_ascii=False)};\n"
        f"window.SUPPORT_TIERS_LATEST = {json.dumps(tiers_latest, ensure_ascii=False)};\n"
        f"window.SUPPORT_TIERS_ANNUAL = {json.dumps(annual, ensure_ascii=False)};\n"
    )
    out.write_text(body, encoding="utf-8")
    return out


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("xlsx", type=Path, help="Path to support-local-authority .xlsx")
    p.add_argument("out_dir", type=Path, nargs="?", default=Path("data"),
                   help="Output directory (default: data/)")
    args = p.parse_args()

    if not args.xlsx.exists():
        print(f"error: {args.xlsx} does not exist", file=sys.stderr)
        return 2
    args.out_dir.mkdir(parents=True, exist_ok=True)

    rows, meta, tiers_latest, annual = build_support(args.xlsx)
    out = write_js(args.out_dir, rows, meta, tiers_latest, annual)
    print(
        f"wrote {out} — {len(rows)} regions as at {meta['date']} "
        f"(total {sum(r['v'] for r in rows):,}); "
        f"tiers S95={tiers_latest['s95']:,} S98={tiers_latest['s98']:,} S4={tiers_latest['s4']:,} "
        f"over {len(annual)} snapshots"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
