"""
Build `data/nat-quarterly-data.js` — top-N nationalities across the last 8
quarters of Asy_D01 (main-applicant claims).

Source: `asylum-claims-datasets-<YYYY>.xlsx` from gov.uk.

Emits `window.NAT_QUARTERLY = {quarters: [...8], series: [{name, data: [8]}]}`
where `series` contains the top-20 nationalities ranked by total applications
across the eight-quarter window.

Usage:
    python scripts/build_nat_quarterly.py <path/to/asylum-claims-datasets.xlsx> data/
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd


TOP_N = 20
QUARTERS_BACK = 8


def quarter_sort_key(q: str) -> tuple[int, int]:
    """'2024 Q3' → (2024, 3) for deterministic ordering."""
    year, quarter = q.split(" Q")
    return int(year), int(quarter)


def build_nat_quarterly(xlsx_path: Path) -> tuple[dict, dict]:
    apps = pd.read_excel(xlsx_path, sheet_name="Data_Asy_D01", engine="openpyxl", header=1)
    apps = apps[apps["Applicant type"] == "Main Applicant"]

    all_quarters = sorted(apps["Quarter"].dropna().unique(), key=quarter_sort_key)
    recent = all_quarters[-QUARTERS_BACK:]
    window = apps[apps["Quarter"].isin(recent)]

    # Rank by total claims across the window
    totals = window.groupby("Nationality")["Claims"].sum().sort_values(ascending=False)
    top = totals.head(TOP_N).index.tolist()

    # Build pivot: rows = nationality, cols = quarter
    pivot = (
        window[window["Nationality"].isin(top)]
        .groupby(["Nationality", "Quarter"])["Claims"].sum()
        .unstack(fill_value=0)
        .reindex(index=top, columns=recent, fill_value=0)
    )

    series = [
        {"name": nat, "data": [int(v) for v in pivot.loc[nat].tolist()]}
        for nat in top
    ]

    payload = {"quarters": list(recent), "series": series}

    meta = {
        "source": xlsx_path.name,
        "generatedAt": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "provider": "UK Home Office",
        "licence": "Open Government Licence v3.0",
        "sourceUrl": "https://www.gov.uk/government/statistical-data-sets/immigration-system-statistics-data-tables",
        "topN": TOP_N,
        "quartersCovered": len(recent),
    }
    return payload, meta


def write_js(out_dir: Path, payload: dict, meta: dict) -> Path:
    out = out_dir / "nat-quarterly-data.js"
    body = (
        "/* AUTO-GENERATED by scripts/build_nat_quarterly.py. Do not edit. */\n"
        f"window.NAT_QUARTERLY = {json.dumps(payload, ensure_ascii=False)};\n"
        f"window.NAT_QUARTERLY_META = {json.dumps(meta, ensure_ascii=False)};\n"
    )
    out.write_text(body, encoding="utf-8")
    return out


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("xlsx", type=Path, help="Path to asylum-claims-datasets .xlsx")
    p.add_argument("out_dir", type=Path, nargs="?", default=Path("data"))
    args = p.parse_args()

    if not args.xlsx.exists():
        print(f"error: {args.xlsx} does not exist", file=sys.stderr)
        return 2
    args.out_dir.mkdir(parents=True, exist_ok=True)

    payload, meta = build_nat_quarterly(args.xlsx)
    out = write_js(args.out_dir, payload, meta)
    print(f"wrote {out} - {len(payload['series'])} series x {len(payload['quarters'])} quarters "
          f"({payload['quarters'][0]} -> {payload['quarters'][-1]})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
