"""
Build `data/resettlement-data.js` - persons resettled under each UK scheme
for the most recent three complete calendar years.

Source: `resettlement-scheme-datasets-<mmm-YYYY>.xlsx` from gov.uk.
  https://www.gov.uk/government/statistical-data-sets/immigration-system-statistics-data-tables

Emits `window.RESETTLEMENT_SERIES = [{name, <year>: persons, ...}]`.

Schemes reported (grouping from `Resettlement Scheme Subgroup` + the
`Community Sponsorship` flag):
  - UK Resettlement Scheme (UKRS)
  - ACRS (sum of Pathway 1 + 2 + 3)
  - ARAP (subgroup "ARAP & ARR")
  - Community Sponsorship (rows where the flag is non-null)
  - Mandate Scheme
  - Gateway / VPRS / VCRS included only if non-zero in window

Note: Ukraine Family Scheme / Homes for Ukraine are tracked in a separate
publication and are NOT in this file.

Usage:
    python scripts/build_resettlement.py <path/to/resettlement-scheme-datasets.xlsx> data/
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd


ACRS_SUBGROUPS = {"ACRS Pathway 1", "ACRS Pathway 2", "ACRS Pathway 3"}

# Display order when they appear in the output
SCHEME_ORDER = [
    "ACRS",
    "ARAP",
    "UK Resettlement Scheme",
    "Community Sponsorship",
    "Mandate Scheme",
    "Gateway Protection Programme",
    "Vulnerable Persons Resettlement Scheme",
    "Vulnerable Children Resettlement Scheme",
]


def pick_latest_complete_years(df: pd.DataFrame, n: int = 3) -> list[int]:
    """Last n years with all four quarters present."""
    by_year = df.groupby("Year")["Quarter"].nunique()
    full = sorted(by_year[by_year >= 4].index)
    return full[-n:]


def classify(row) -> str | None:
    """Map a row to one of the output scheme buckets. Return None to drop."""
    sub = row["Resettlement Scheme Subgroup"]
    comm = row["Community Sponsorship"]

    # Community-sponsored rows go into a standalone bucket regardless of scheme.
    if isinstance(comm, str) and comm.strip():
        return "Community Sponsorship"

    if sub in ACRS_SUBGROUPS:
        return "ACRS"
    if sub == "ARAP & ARR":
        return "ARAP"
    if isinstance(sub, str):
        return sub
    return None


def build_resettlement(xlsx_path: Path) -> tuple[list[dict], dict]:
    df = pd.read_excel(xlsx_path, sheet_name="Data_Res_D02", engine="openpyxl", header=1)

    years = pick_latest_complete_years(df, 3)
    window = df[df["Year"].isin(years)].copy()
    window["Bucket"] = window.apply(classify, axis=1)
    window = window[window["Bucket"].notna()]

    pivot = (
        window.groupby(["Bucket", "Year"])["Persons"].sum()
        .unstack(fill_value=0)
        .reindex(columns=years, fill_value=0)
    )

    rows: list[dict] = []
    for name in SCHEME_ORDER:
        if name not in pivot.index:
            continue
        row = {"name": name}
        for y in years:
            row[str(y)] = int(pivot.loc[name, y])
        if sum(row[str(y)] for y in years) == 0:
            continue
        rows.append(row)

    # Any buckets not in SCHEME_ORDER (future schemes) - append by name.
    for name in sorted(pivot.index):
        if name in SCHEME_ORDER:
            continue
        row = {"name": name}
        for y in years:
            row[str(y)] = int(pivot.loc[name, y])
        if sum(row[str(y)] for y in years) == 0:
            continue
        rows.append(row)

    meta = {
        "source": xlsx_path.name,
        "generatedAt": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "provider": "UK Home Office",
        "licence": "Open Government Licence v3.0",
        "sourceUrl": "https://www.gov.uk/government/statistical-data-sets/immigration-system-statistics-data-tables",
        "years": [int(y) for y in years],
        "notes": [
            "ACRS = Afghan Citizens Resettlement Scheme (Pathways 1 + 2 + 3 summed).",
            "ARAP = Afghan Relocations and Assistance Policy, including ARR legacy cases.",
            "Community-sponsored rows are pulled into their own bucket regardless of the base scheme.",
            "Ukraine schemes (Family Scheme / Homes for Ukraine) are tracked in a separate publication and are NOT included.",
        ],
    }
    return rows, meta


def write_js(out_dir: Path, rows: list[dict], meta: dict) -> Path:
    out = out_dir / "resettlement-data.js"
    body = (
        "/* AUTO-GENERATED by scripts/build_resettlement.py. Do not edit. */\n"
        f"window.RESETTLEMENT_SERIES = {json.dumps(rows, ensure_ascii=False)};\n"
        f"window.RESETTLEMENT_META = {json.dumps(meta, ensure_ascii=False)};\n"
    )
    out.write_text(body, encoding="utf-8")
    return out


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("xlsx", type=Path, help="Path to resettlement-scheme-datasets .xlsx")
    p.add_argument("out_dir", type=Path, nargs="?", default=Path("data"))
    args = p.parse_args()

    if not args.xlsx.exists():
        print(f"error: {args.xlsx} does not exist", file=sys.stderr)
        return 2
    args.out_dir.mkdir(parents=True, exist_ok=True)

    rows, meta = build_resettlement(args.xlsx)
    out = write_js(args.out_dir, rows, meta)
    years = meta["years"]
    print(f"wrote {out} - {len(rows)} schemes x {len(years)} years ({years[0]}-{years[-1]})")
    for r in rows:
        cells = ", ".join(f"{y}={r[str(y)]:,}" for y in years)
        print(f"  {r['name']}: {cells}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
