"""
Build `data/returns-data.js` — returns from the UK by nationality, latest
complete year in the source.

Source: `returns-datasets-<mmm-YYYY>.xlsx` from gov.uk.
  https://www.gov.uk/government/statistical-data-sets/immigration-system-statistics-data-tables

Emits `window.RETURNS_BY_NATIONALITY = [{name, region, enforced, voluntary, refused, total}]`
and `window.RETURNS_META = {...}`.

Usage:
    python scripts/build_returns.py <path/to/returns-datasets.xlsx> data/

Design
------
- Reads sheet `Data_Ret_D01` (returns by nationality).
- Filters to the latest year present; sums Number of returns by
  nationality, region, and Return type group.
- Output is sorted by total returns descending and deterministic.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd


ENFORCED = "Enforced return"
VOLUNTARY = "Voluntary return"
REFUSED = "Refused entry at port and subsequently departed"


def pick_latest_year(df: pd.DataFrame) -> int:
    """Latest year with all four quarters reported."""
    by_year = df.groupby("Year")["Quarter"].nunique()
    full_years = by_year[by_year >= 4].index
    if len(full_years) == 0:
        return int(by_year.index.max())
    return int(full_years.max())


def build_returns(xlsx_path: Path) -> tuple[list[dict], dict]:
    df = pd.read_excel(xlsx_path, sheet_name="Data_Ret_D01", engine="openpyxl", header=1)

    year = pick_latest_year(df)
    latest = df[df["Year"] == year].copy()

    # Map region label in this publication to our canonical short form.
    # The returns sheet uses "Africa North"/"Asia Central" — the app's
    # REGION_MAP uses nationality names, so we keep the region column
    # verbatim and let the UI layer do any grouping it wants.
    pivot = (
        latest.groupby(["Nationality", "Region", "Return type group"])[
            "Number of returns"
        ]
        .sum()
        .unstack(fill_value=0)
    )

    rows: list[dict] = []
    for (nat, region), row in pivot.iterrows():
        enforced = int(row.get(ENFORCED, 0))
        voluntary = int(row.get(VOLUNTARY, 0))
        refused = int(row.get(REFUSED, 0))
        total = enforced + voluntary + refused
        if total <= 0:
            continue
        rows.append({
            "name": nat,
            "region": region,
            "enforced": enforced,
            "voluntary": voluntary,
            "refused": refused,
            "total": total,
        })

    rows.sort(key=lambda r: r["total"], reverse=True)

    # Prior-year total so the Dashboard card can show a YoY delta without a
    # second data load. Uses the four main return types summed across all
    # nationalities in the year before `year`.
    prior_year = year - 1
    prior = df[df["Year"] == prior_year]
    if len(prior):
        prior_total = int(
            prior[prior["Return type group"].isin([ENFORCED, VOLUNTARY, REFUSED])][
                "Number of returns"
            ].sum()
        )
    else:
        prior_total = None

    total_latest = sum(r["total"] for r in rows)

    meta = {
        "year": year,
        "totalYear": total_latest,
        "priorYear": prior_year if prior_total is not None else None,
        "priorYearTotal": prior_total,
        "source": xlsx_path.name,
        "generatedAt": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "provider": "UK Home Office",
        "licence": "Open Government Licence v3.0",
        "sourceUrl": "https://www.gov.uk/government/statistical-data-sets/immigration-system-statistics-data-tables",
    }
    return rows, meta


def write_js(out_dir: Path, rows: list[dict], meta: dict) -> Path:
    out = out_dir / "returns-data.js"
    body = (
        "/* AUTO-GENERATED by scripts/build_returns.py. Do not edit. */\n"
        f"window.RETURNS_BY_NATIONALITY = {json.dumps(rows, ensure_ascii=False)};\n"
        f"window.RETURNS_META = {json.dumps(meta, ensure_ascii=False)};\n"
    )
    out.write_text(body, encoding="utf-8")
    return out


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("xlsx", type=Path, help="Path to returns-datasets .xlsx")
    p.add_argument("out_dir", type=Path, nargs="?", default=Path("data"),
                   help="Output directory (default: data/)")
    args = p.parse_args()

    if not args.xlsx.exists():
        print(f"error: {args.xlsx} does not exist", file=sys.stderr)
        return 2
    args.out_dir.mkdir(parents=True, exist_ok=True)

    rows, meta = build_returns(args.xlsx)
    out = write_js(args.out_dir, rows, meta)
    print(f"wrote {out} - {len(rows)} nationalities, year {meta['year']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
