"""
Build `data/decisions-data.js` — initial asylum decisions for the latest
complete year in the source, broken down by case outcome group.

Source: `asylum-claims-datasets-<YYYY>.xlsx` (sheet Data_Asy_D02).
  https://www.gov.uk/government/statistical-data-sets/immigration-system-statistics-data-tables

Emits:
  window.DECISIONS_LATEST = [{label, v, color}]   — same shape as legacy DECISIONS_2024
  window.DECISIONS_META   = {year, source, ...}

Usage:
    python scripts/build_decisions.py <path/to/asylum-claims-datasets.xlsx> data/

Design
------
- Reads Data_Asy_D02, filters to Main Applicant, latest full year (all 4 quarters).
- Groups by Case outcome group, sums Decisions.
- Emits four rows in display order:
    Grant of Protection        → label 'Granted asylum'
    Grant of Other Leave       → label 'Granted humanitarian / other'
    Refused                    → label 'Refused'
    Withdrawn + Administrative → label 'Withdrawn / admin'
- Colors match the app's CSS token palette; order is fixed so index-based
  grant-rate computation works: grant = (rows[0].v + rows[1].v) / total.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd


def pick_latest_year(df: pd.DataFrame) -> int:
    """Latest year with all four quarters reported for Main Applicants."""
    main = df[df["Applicant type"] == "Main Applicant"]
    by_year = main.groupby("Year")["Quarter"].nunique()
    full_years = by_year[by_year >= 4].index
    if len(full_years) == 0:
        return int(by_year.index.max())
    return int(full_years.max())


def build_decisions(xlsx_path: Path) -> tuple[list[dict], dict]:
    df = pd.read_excel(xlsx_path, sheet_name="Data_Asy_D02", engine="openpyxl", header=1)

    year = pick_latest_year(df)
    latest = df[(df["Year"] == year) & (df["Applicant type"] == "Main Applicant")]
    by_group = latest.groupby("Case outcome group")["Decisions"].sum()

    grant_prot  = int(by_group.get("Grant of Protection", 0))
    grant_other = int(by_group.get("Grant of Other Leave", 0))
    refused     = int(by_group.get("Refused", 0))
    withdrawn   = int(by_group.get("Withdrawn", 0)) + int(by_group.get("Administrative Outcome", 0))

    rows = [
        {"label": "Granted asylum",                 "v": grant_prot,  "color": "var(--accent-2)"},
        {"label": "Granted humanitarian / other",   "v": grant_other, "color": "var(--accent-gold)"},
        {"label": "Refused",                         "v": refused,     "color": "var(--accent-warn)"},
        {"label": "Withdrawn / admin",               "v": withdrawn,   "color": "var(--muted-2)"},
    ]

    meta = {
        "year": year,
        "source": xlsx_path.name,
        "generatedAt": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "provider": "UK Home Office",
        "licence": "Open Government Licence v3.0",
        "sourceUrl": (
            "https://www.gov.uk/government/statistical-data-sets/"
            "immigration-system-statistics-data-tables"
        ),
    }
    return rows, meta


def write_js(out_dir: Path, rows: list[dict], meta: dict) -> Path:
    out = out_dir / "decisions-data.js"
    body = (
        "/* AUTO-GENERATED by scripts/build_decisions.py. Do not edit. */\n"
        f"window.DECISIONS_LATEST = {json.dumps(rows, ensure_ascii=False)};\n"
        f"window.DECISIONS_META   = {json.dumps(meta, ensure_ascii=False)};\n"
    )
    out.write_text(body, encoding="utf-8")
    return out


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("xlsx", type=Path, help="Path to asylum-claims-datasets .xlsx")
    p.add_argument("out_dir", type=Path, nargs="?", default=Path("data"),
                   help="Output directory (default: data/)")
    args = p.parse_args()

    if not args.xlsx.exists():
        print(f"error: {args.xlsx} does not exist", file=sys.stderr)
        return 2
    args.out_dir.mkdir(parents=True, exist_ok=True)

    rows, meta = build_decisions(args.xlsx)
    out = write_js(args.out_dir, rows, meta)
    total = sum(r["v"] for r in rows)
    grant = rows[0]["v"] + rows[1]["v"]
    print(f"wrote {out} — year {meta['year']}, {total:,} decisions, grant rate {grant/total:.1%}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
