"""
Build `data/sex-age-data.js` — annual sex and age breakdown of asylum applicants.

Source: `asylum-claims-datasets-<YYYY>.xlsx` from gov.uk (same file as NAT_FULL).
  Sheet: Data_Asy_D01

Emits:
  window.SEX_AGE_ANNUAL = [{y, male, female, under18, adult, total}]
    y        — calendar year
    male     — main applicants recorded as Male
    female   — main applicants recorded as Female
    under18  — main applicants aged Under 18 (UASC included)
    adult    — main applicants aged 18+ (sum of 18-29, 30-49, 50-69, 70+)
    total    — all main applicants (including Unknown Sex / Unknown Age)
  window.SEX_AGE_META = {latest_year, source, generatedAt, ...}

Notes:
- Age and Sex fields exist only from 2009 onwards. Pre-2009 rows carry
  'Total (pre-2009)' in those columns and are excluded from sex/age counts
  (they are still counted in `total` via the total-row filter below).
- 'Unknown Sex' and 'Unknown Age' are included in `total` but excluded from
  the male/female and under18/adult breakdowns so ratios remain interpretable.
- Series starts from 2009 (first year with full Sex/Age breakdown).

Usage:
    python scripts/build_sex_age.py <path/to/asylum-claims-datasets.xlsx> data/
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

SERIES_START = 2009
ADULT_AGES = {"18-29", "30-49", "50-69", "70+"}


def build_sex_age(xlsx_path: Path) -> tuple[list[dict], dict]:
    df = pd.read_excel(xlsx_path, sheet_name="Data_Asy_D01", engine="openpyxl", header=1)
    main = df[df["Applicant type"] == "Main Applicant"].copy()

    years = sorted(y for y in main["Year"].unique() if y >= SERIES_START)

    rows: list[dict] = []
    for year in years:
        y_df = main[main["Year"] == year]

        male = int(y_df[y_df["Sex"] == "Male"]["Claims"].sum())
        female = int(y_df[y_df["Sex"] == "Female"]["Claims"].sum())
        under18 = int(y_df[y_df["Age"] == "Under 18"]["Claims"].sum())
        adult = int(y_df[y_df["Age"].isin(ADULT_AGES)]["Claims"].sum())

        # Cross-tab: male/female among adults only
        adult_mask = y_df["Age"].isin(ADULT_AGES)
        male_adult = int(y_df[adult_mask & (y_df["Sex"] == "Male")]["Claims"].sum())
        female_adult = int(y_df[adult_mask & (y_df["Sex"] == "Female")]["Claims"].sum())

        # Total: deduplicate by summing rows where Sex is Male or Female
        # (avoids double-counting Unknown rows).  If neither is reported use Claims directly.
        total_from_sex = male + female
        unknown_sex = int(y_df[y_df["Sex"] == "Unknown Sex"]["Claims"].sum())
        total = total_from_sex + unknown_sex if total_from_sex > 0 else int(y_df["Claims"].sum())

        if total <= 0:
            continue
        rows.append({
            "y": int(year),
            "male": male,
            "female": female,
            "male_adult": male_adult,
            "female_adult": female_adult,
            "under18": under18,
            "adult": adult,
            "total": total,
        })

    latest_year = rows[-1]["y"] if rows else None
    meta = {
        "latest_year": latest_year,
        "series_start": SERIES_START,
        "source": xlsx_path.name,
        "generatedAt": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "provider": "UK Home Office",
        "licence": "Open Government Licence v3.0",
        "sourceUrl": (
            "https://www.gov.uk/government/statistical-data-sets/"
            "immigration-system-statistics-data-tables"
        ),
        "notes": (
            "Main applicants only. Sex and Age fields available from 2009. "
            "Unknown Sex/Age included in total but excluded from breakdowns."
        ),
    }
    return rows, meta


def write_js(out_dir: Path, rows: list[dict], meta: dict) -> Path:
    out = out_dir / "sex-age-data.js"
    body = (
        "/* AUTO-GENERATED by scripts/build_sex_age.py. Do not edit. */\n"
        f"window.SEX_AGE_ANNUAL = {json.dumps(rows, ensure_ascii=False)};\n"
        f"window.SEX_AGE_META   = {json.dumps(meta, ensure_ascii=False)};\n"
    )
    out.write_text(body, encoding="utf-8")
    return out


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("xlsx", type=Path, help="Path to asylum-claims-datasets .xlsx")
    p.add_argument("out_dir", type=Path, nargs="?", default=Path("data"),
                   help="Output directory (default: data/)")
    args = p.parse_args()

    if not args.xlsx.exists():
        print(f"error: {args.xlsx} does not exist", file=sys.stderr)
        return 2
    args.out_dir.mkdir(parents=True, exist_ok=True)

    rows, meta = build_sex_age(args.xlsx)
    out = write_js(args.out_dir, rows, meta)
    latest = rows[-1] if rows else {}
    print(  # lgtm[py/clear-text-logging-sensitive-data]
        f"wrote {out} — {len(rows)} years, "
        f"latest {latest.get('y')}: {latest.get('male',0):,}M / {latest.get('female',0):,}F, "
        f"{latest.get('under18',0):,} under-18"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
