"""
Build `data/nat-series-data.js` — annual application counts for the top five
nationalities from 2020 to the latest complete year, derived from ASY_D01.

Source: `asylum-claims-datasets-<YYYY>.xlsx` (sheet Data_Asy_D01).
  https://www.gov.uk/government/statistical-data-sets/immigration-system-statistics-data-tables

Emits:
  window.NAT_SERIES_LATEST = {years: [int, ...], series: [{name, data: [int, ...]}]}
  window.NAT_SERIES_META   = {year_start, year_end, source, ...}

Usage:
    python scripts/build_nat_series.py <path/to/asylum-claims-datasets.xlsx> data/

Design
------
- Reads Data_Asy_D01, filters to Main Applicant.
- Picks five tracked nationalities (Pakistan, Afghanistan, Iran, Eritrea, Syria)
  which are the top-5 the app has always shown.  The list is fixed so the legend
  is stable across releases; absolute rank may vary.
- Builds a series from 2020 to the latest full year (all 4 quarters reported).
- Emits integer counts; missing year → 0.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd


TRACKED = ["Pakistan", "Afghanistan", "Iran", "Eritrea", "Syria"]
YEAR_START = 2020


def pick_latest_year(df: pd.DataFrame) -> int:
    """Latest year with all four quarters reported for Main Applicants."""
    main = df[df["Applicant type"] == "Main Applicant"]
    by_year = main.groupby("Year")["Quarter"].nunique()
    full_years = by_year[by_year >= 4].index
    if len(full_years) == 0:
        return int(by_year.index.max())
    return int(full_years.max())


def build_nat_series(xlsx_path: Path) -> tuple[dict, dict]:
    df = pd.read_excel(xlsx_path, sheet_name="Data_Asy_D01", engine="openpyxl", header=1)

    year_end = pick_latest_year(df)
    main = df[(df["Applicant type"] == "Main Applicant") &
              (df["Year"] >= YEAR_START) & (df["Year"] <= year_end)]

    years = list(range(YEAR_START, year_end + 1))

    series = []
    for nat in TRACKED:
        annual = main[main["Nationality"] == nat].groupby("Year")["Claims"].sum()
        data = [int(annual.get(y, 0)) for y in years]
        series.append({"name": nat, "data": data})

    result = {"years": years, "series": series}

    meta = {
        "year_start": YEAR_START,
        "year_end": year_end,
        "source": xlsx_path.name,
        "generatedAt": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "provider": "UK Home Office",
        "licence": "Open Government Licence v3.0",
        "sourceUrl": (
            "https://www.gov.uk/government/statistical-data-sets/"
            "immigration-system-statistics-data-tables"
        ),
    }
    return result, meta


def write_js(out_dir: Path, result: dict, meta: dict) -> Path:
    out = out_dir / "nat-series-data.js"
    body = (
        "/* AUTO-GENERATED by scripts/build_nat_series.py. Do not edit. */\n"
        f"window.NAT_SERIES_LATEST = {json.dumps(result, ensure_ascii=False)};\n"
        f"window.NAT_SERIES_META   = {json.dumps(meta, ensure_ascii=False)};\n"
    )
    out.write_text(body, encoding="utf-8")
    return out


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("xlsx", type=Path, help="Path to asylum-claims-datasets .xlsx")
    p.add_argument("out_dir", type=Path, nargs="?", default=Path("data"),
                   help="Output directory (default: data/)")
    args = p.parse_args()

    if not args.xlsx.exists():
        print(f"error: {args.xlsx} does not exist", file=sys.stderr)
        return 2
    args.out_dir.mkdir(parents=True, exist_ok=True)

    result, meta = build_nat_series(args.xlsx)
    out = write_js(out_dir=args.out_dir, result=result, meta=meta)
    print(f"wrote {out} — {meta['year_start']}–{meta['year_end']}, {len(result['series'])} series")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
