"""
Build `data/age-disputes-data.js` — age-dispute cases raised and resolved
by nationality, latest complete year in the source.

Source: `age-disputes-datasets-<mmm-YYYY>.xlsx` from gov.uk.
  https://www.gov.uk/government/statistical-data-sets/immigration-system-statistics-data-tables

Emits `window.AGE_DISPUTES_BY_NATIONALITY = [{name, region, raised, resolved_over_18, resolved_under_18}]`
and `window.AGE_DISPUTES_META = {...}`.

Usage:
    python scripts/build_age_disputes.py <path/to/age-disputes-datasets.xlsx> data/

Design
------
- Reads sheet `Data_Asy_D05`.
- `raised` sums rows where Raised or resolved == 'Raised' (both raised types).
- `resolved_over_18` / `resolved_under_18` split rows where Raised or resolved
  == 'Resolved' by the 18+/<18 outcome.
- Sorted by raised desc, deterministic.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd


def pick_latest_year(df: pd.DataFrame) -> int:
    """Latest year with all four quarters reported."""
    by_year = df.groupby("Year")["Quarter"].nunique()
    full_years = by_year[by_year >= 4].index
    if len(full_years) == 0:
        return int(by_year.index.max())
    return int(full_years.max())


def build_age_disputes(xlsx_path: Path) -> tuple[list[dict], dict]:
    df = pd.read_excel(xlsx_path, sheet_name="Data_Asy_D05", engine="openpyxl", header=1)

    year = pick_latest_year(df)
    latest = df[df["Year"] == year]

    raised = (
        latest[latest["Raised or resolved"] == "Raised"]
        .groupby(["Nationality", "Region"])["Age disputes"].sum()
    )
    resolved_over = (
        latest[(latest["Raised or resolved"] == "Resolved") &
               (latest["Raised type / Resolved outcome"] == "18+")]
        .groupby(["Nationality", "Region"])["Age disputes"].sum()
    )
    resolved_under = (
        latest[(latest["Raised or resolved"] == "Resolved") &
               (latest["Raised type / Resolved outcome"] == "Less than 18")]
        .groupby(["Nationality", "Region"])["Age disputes"].sum()
    )

    keys = sorted(
        set(raised.index) | set(resolved_over.index) | set(resolved_under.index),
        key=lambda k: (-int(raised.get(k, 0)), k[0])
    )

    rows: list[dict] = []
    for (nat, region) in keys:
        r = int(raised.get((nat, region), 0))
        ro = int(resolved_over.get((nat, region), 0))
        ru = int(resolved_under.get((nat, region), 0))
        if r == 0 and ro == 0 and ru == 0:
            continue
        rows.append({
            "name": nat,
            "region": region,
            "raised": r,
            "resolved_over_18": ro,
            "resolved_under_18": ru,
        })

    meta = {
        "year": year,
        "source": xlsx_path.name,
        "generatedAt": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "provider": "UK Home Office",
        "licence": "Open Government Licence v3.0",
        "sourceUrl": "https://www.gov.uk/government/statistical-data-sets/immigration-system-statistics-data-tables",
    }
    return rows, meta


def write_js(out_dir: Path, rows: list[dict], meta: dict) -> Path:
    out = out_dir / "age-disputes-data.js"
    body = (
        "/* AUTO-GENERATED by scripts/build_age_disputes.py. Do not edit. */\n"
        f"window.AGE_DISPUTES_BY_NATIONALITY = {json.dumps(rows, ensure_ascii=False)};\n"
        f"window.AGE_DISPUTES_META = {json.dumps(meta, ensure_ascii=False)};\n"
    )
    out.write_text(body, encoding="utf-8")
    return out


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("xlsx", type=Path, help="Path to age-disputes-datasets .xlsx")
    p.add_argument("out_dir", type=Path, nargs="?", default=Path("data"),
                   help="Output directory (default: data/)")
    args = p.parse_args()

    if not args.xlsx.exists():
        print(f"error: {args.xlsx} does not exist", file=sys.stderr)
        return 2
    args.out_dir.mkdir(parents=True, exist_ok=True)

    rows, meta = build_age_disputes(args.xlsx)
    out = write_js(args.out_dir, rows, meta)
    print(f"wrote {out} - {len(rows)} nationalities, year {meta['year']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
