"""
Build `data/route-of-entry-data.js` — asylum claims by route of entry.

Source: `Data_Asy_D01a` sheet of `asylum-claims-datasets-<YYYY>.xlsx` from gov.uk.
  https://www.gov.uk/government/statistical-data-sets/immigration-system-statistics-data-tables

The sheet splits every quarterly asylum-claim count into a top-level group
(Illegal Entry Routes / Visas and Other Leave / Other) and a sub-route (Small
Boat, Clandestine, Entered Without Relevant Documentation, Study Visa,
Work Visa, Visitor Visa, Other Leave, Other). Counts are of people, including
dependants — `Data_Asy_D01` is the main-applicant-only source used by
build_nat_full.py; the two totals therefore differ by construction.

Important: `Asy_D01a` records claims by the DATE OF ASYLUM CLAIM. The IER
dataset (illegal-entry-routes-to-the-uk) records people by ARRIVAL DATE, so
the two series are not directly comparable — call this out in any view that
mixes them.

Emits:
  window.ROUTE_OF_ENTRY_QUARTERLY = [{q, group, sub, v}]
    - q: "YYYY Q1".."YYYY Q4"
    - group: one of the three top-level Route-of-entry groups
    - sub: the sub-route label
    - v: integer claim count (people)
  window.ROUTE_OF_ENTRY_META = {year, latestQuarter, source, generatedAt, ...}

`year` is the latest year with four quarters reported, matching NAT_FULL's
cadence so the Flow system-flow sankey aggregates the same period.

Usage:
    python scripts/build_route_of_entry.py <path/to/asylum-claims-datasets.xlsx> data/
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd


SHEET = "Data_Asy_D01a"
COL_GROUP = "Route of entry group"
COL_SUB = "Route of entry / Latest leave prior to claim"


def _quarter_key(q: str) -> tuple[int, int]:
    y, n = q.split(" Q")
    return int(y), int(n)


def pick_latest_full_year(quarters: list[str]) -> int:
    """Latest year for which all four quarter labels are present."""
    by_year: dict[int, set[int]] = {}
    for q in quarters:
        y, n = _quarter_key(q)
        by_year.setdefault(y, set()).add(n)
    full = [y for y, qs in by_year.items() if qs >= {1, 2, 3, 4}]
    if full:
        return max(full)
    return max(by_year)


def build(xlsx_path: Path) -> tuple[list[dict], dict]:
    df = pd.read_excel(xlsx_path, sheet_name=SHEET, engine="openpyxl", header=1)

    rows: list[dict] = []
    for _, r in df.iterrows():
        q = r["Quarter"]
        v = r["Claims"]
        if pd.isna(q) or pd.isna(v):
            continue
        try:
            vi = int(v)
        except (TypeError, ValueError):
            continue
        if vi <= 0:
            continue
        rows.append({
            "q": str(q),
            "group": str(r[COL_GROUP]),
            "sub": str(r[COL_SUB]),
            "v": vi,
        })

    rows.sort(key=lambda r: (_quarter_key(r["q"]), r["group"], r["sub"]))

    quarters = sorted({r["q"] for r in rows}, key=_quarter_key)
    latest_quarter = quarters[-1] if quarters else None
    year = pick_latest_full_year(quarters) if quarters else None

    meta = {
        "year": year,
        "latestQuarter": latest_quarter,
        "source": xlsx_path.name,
        "generatedAt": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "provider": "UK Home Office",
        "licence": "Open Government Licence v3.0",
        "sourceUrl": "https://www.gov.uk/government/statistical-data-sets/immigration-system-statistics-data-tables",
        "sheet": SHEET,
        "basis": "Date of asylum claim (differs from IER arrival-date basis)",
    }
    return rows, meta


def write_js(out_dir: Path, rows: list[dict], meta: dict) -> Path:
    out = out_dir / "route-of-entry-data.js"
    body = (
        "/* AUTO-GENERATED by scripts/build_route_of_entry.py. Do not edit. */\n"
        f"window.ROUTE_OF_ENTRY_QUARTERLY = {json.dumps(rows, ensure_ascii=False, separators=(',', ':'))};\n"
        f"window.ROUTE_OF_ENTRY_META = {json.dumps(meta, ensure_ascii=False)};\n"
    )
    out.write_text(body, encoding="utf-8")
    return out


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("xlsx", type=Path, help="Path to asylum-claims-datasets .xlsx")
    p.add_argument("out_dir", type=Path, nargs="?", default=Path("data"),
                   help="Output directory (default: data/)")
    args = p.parse_args()

    if not args.xlsx.exists():
        print(f"error: {args.xlsx} does not exist", file=sys.stderr)
        return 2
    args.out_dir.mkdir(parents=True, exist_ok=True)

    rows, meta = build(args.xlsx)
    out = write_js(args.out_dir, rows, meta)
    print(f"wrote {out} — {len(rows)} rows, latest quarter {meta['latestQuarter']}, full year {meta['year']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
